import {Link} from 'react-router-dom';
import {ArrowRight,HeartHandshake,Leaf,Users,PackageCheck,UtensilsCrossed,Building2,ShieldCheck} from 'lucide-react';
import {useApi} from '../hooks/useApi';import api from '../services/api';import StatCard from '../components/StatCard';
export default function Home(){const {data,loading}=useApi(()=>api.get('/admin/public-stats').then(r=>r.data.data.stats),[]);return <>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><span/> A little food can make a big difference</span><h1>Turn surplus food into <em>community support.</em></h1><p>FoodShare Lanka connects restaurants, bakeries, hotels, supermarkets and households with organizations that can collect and redistribute safe surplus food.</p><div className="hero-actions"><Link className="btn btn-primary" to="/register?role=DONOR">Donate Food <ArrowRight size={18}/></Link><Link className="btn btn-light" to="/donations">Find Food</Link><a className="hero-secondary" href="#how-it-works">How it works</a></div><div className="trust-row"><span><ShieldCheck size={17}/> Simple & responsible</span><span><Leaf size={17}/> Less food waste</span></div></div><div className="hero-art"><div className="hero-card main"><div className="hero-card-icon"><HeartHandshake/></div><div><b>Today's community impact</b><strong>{loading?'—':`${data?.totalItemsRedistributed||0}+`}</strong><span>food items redistributed</span></div></div><div className="hero-card mini one"><UtensilsCrossed/><span>Surplus meals</span></div><div className="hero-card mini two"><Users/><span>Community partners</span></div><div className="leaf-shape"/></div></div></section>
<section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">The problem</span><h2>Surplus food and food needs can exist side by side.</h2></div><p>Surplus food can become waste while charities and community organizations need food support. The gap is often simple: the right people need a reliable way to connect.</p></div><div className="feature-grid"><Feature icon={<PackageCheck/>} title="Rescue usable food" text="Publish surplus food before it becomes waste, with clear quantity, condition and collection details."/><Feature icon={<Building2/>} title="Connect organizations" text="Recipient organizations can discover suitable donations by location, category and availability."/><Feature icon={<HeartHandshake/>} title="Track the handover" text="Requests move from pending to accepted, collected and completed so everyone knows what happens next."/></div><div className="solution-strip"><div><span className="eyebrow">The solution</span><h3>One simple place to publish, discover and track surplus food.</h3></div><p>FoodShare Lanka gives donors a clear way to list safe food and gives recipient organizations the tools to find suitable donations, request them and track the handover.</p></div></div></section>
<section className="section impact"><div className="container"><div className="section-heading centered"><span className="eyebrow">Live platform impact</span><h2>Every completed donation counts.</h2><p>These numbers update from application data rather than a static mock-up.</p></div><div className="stats-grid"><StatCard label="Total donations" value={loading?'—':data?.totalDonations||0} icon={<PackageCheck/>}/><StatCard label="Completed donations" value={loading?'—':data?.completedDonations||0} icon={<HeartHandshake/>}/><StatCard label="Items / meals redistributed" value={loading?'—':data?.totalItemsRedistributed||0} icon={<UtensilsCrossed/>}/><StatCard label="Active donors" value={loading?'—':data?.donors||0} icon={<Users/>}/></div></div></section>
<section id="how-it-works" className="section how"><div className="container"><div className="section-heading centered"><span className="eyebrow">How it works</span><h2>From surplus to support in five steps.</h2></div><div className="steps"><Step n="01" title="Register" text="Join as a donor or recipient organization."/><Step n="02" title="Post or browse" text="Donors list food; recipients search what they need."/><Step n="03" title="Request" text="A recipient sends a quantity and pickup request."/><Step n="04" title="Confirm" text="The donor accepts or rejects the request."/><Step n="05" title="Complete" text="Collection happens and the donation is marked complete."/></div></div></section>
<section className="cta"><div className="container cta-inner"><div><span className="eyebrow">Make surplus useful</span><h2>Have food that can still help someone?</h2><p>Share it instead of wasting it.</p></div><Link className="btn btn-primary" to="/register?role=DONOR">Start donating <ArrowRight size={18}/></Link></div></section></>}
function Feature({icon,title,text}){return <div className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>};function Step({n,title,text}){return <div className="step"><span>{n}</span><h3>{title}</h3><p>{text}</p></div>}
