import User from '../models/User.js';
import Donation from '../models/Donation.js';
import Request from '../models/Request.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { HttpError } from '../utils/httpError.js';

export const publicStats=asyncHandler(async(_req,res)=>{const [totalDonations,completedDonations,donors,impact]=await Promise.all([Donation.countDocuments(),Donation.countDocuments({status:'COMPLETED'}),User.countDocuments({role:'DONOR',isActive:true}),Donation.aggregate([{$match:{status:'COMPLETED'}},{$group:{_id:null,total:{$sum:'$quantity'}}}])]);res.json({success:true,data:{stats:{totalDonations,completedDonations,donors,totalItemsRedistributed:impact[0]?.total||0}}});});
export const stats=asyncHandler(async(_req,res)=>{const [totalUsers,donors,recipients,totalDonations,activeDonations,completedDonations,pendingRequests,completedRequests,impact]=await Promise.all([User.countDocuments(),User.countDocuments({role:'DONOR'}),User.countDocuments({role:'RECIPIENT'}),Donation.countDocuments(),Donation.countDocuments({status:{$in:['AVAILABLE','REQUESTED','ACCEPTED','COLLECTED']}}),Donation.countDocuments({status:'COMPLETED'}),Request.countDocuments({status:'PENDING'}),Request.countDocuments({status:'COMPLETED'}),Donation.aggregate([{$match:{status:'COMPLETED'}},{$group:{_id:null,total:{$sum:'$quantity'}}}])]);res.json({success:true,data:{stats:{totalUsers,donors,recipients,totalDonations,activeDonations,completedDonations,pendingRequests,completedRequests,totalItemsRedistributed:impact[0]?.total||0}}});});
export const users=asyncHandler(async(req,res)=>{const users=await User.find().sort({createdAt:-1}).limit(200);res.json({success:true,data:{users}});});
export const donations=asyncHandler(async(req,res)=>{const donations=await Donation.find().populate('donorId','name organizationName').sort({createdAt:-1}).limit(200);res.json({success:true,data:{donations}});});
export const requests=asyncHandler(async(req,res)=>{const requests=await Request.find().populate('recipientId','name organizationName').populate('donorId','name organizationName').populate('donationId','title quantity unit').sort({createdAt:-1}).limit(200);res.json({success:true,data:{requests}});});
export const toggleUser=asyncHandler(async(req,res)=>{const user=await User.findById(req.params.id);if(!user)throw new HttpError(404,'User not found');if(user.role==='ADMIN')throw new HttpError(400,'Admin accounts cannot be disabled here');user.isActive=!user.isActive;await user.save();res.json({success:true,message:`User ${user.isActive?'enabled':'disabled'}`,data:{user}});});
export const removeDonation=asyncHandler(async(req,res)=>{const donation=await Donation.findById(req.params.id);if(!donation)throw new HttpError(404,'Donation not found');donation.status='CANCELLED';await donation.save();await Request.updateMany({donationId:donation._id,status:'PENDING'},{status:'CANCELLED'});res.json({success:true,message:'Donation removed from listings'});});
