import mongoose from 'mongoose';
import Request from '../models/Request.js';
import Donation from '../models/Donation.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { HttpError } from '../utils/httpError.js';
import { requestSchema } from '../utils/validation.js';

export const createRequest=asyncHandler(async(req,res)=>{ const parsed=requestSchema.safeParse(req.body); if(!parsed.success) return res.status(400).json({success:false,message:parsed.error.issues[0].message}); const donation=await Donation.findById(req.body.donationId); if(!donation) throw new HttpError(404,'Donation not found'); if(donation.status!=='AVAILABLE') throw new HttpError(400,'This donation is no longer available'); if(donation.bestBeforeDate<new Date()) throw new HttpError(400,'This donation has expired'); if(parsed.data.requestedQuantity>donation.quantity) throw new HttpError(400,'Requested quantity cannot exceed the available quantity'); const existing=await Request.findOne({donationId:donation._id,recipientId:req.user._id,status:{$in:['PENDING','ACCEPTED','COLLECTED']}}); if(existing) throw new HttpError(409,'You already have an active request for this donation'); const request=await Request.create({...parsed.data,donationId:donation._id,recipientId:req.user._id,donorId:donation.donorId,status:'PENDING'}); donation.status='REQUESTED'; await donation.save(); res.status(201).json({success:true,message:'Donation request submitted',data:{request}}); });
export const myRequests=asyncHandler(async(req,res)=>{const requests=await Request.find({recipientId:req.user._id}).populate('donationId','title category quantity unit city district status').populate('donorId','name organizationName').sort({createdAt:-1});res.json({success:true,data:{requests}});});
export const donorRequests=asyncHandler(async(req,res)=>{const requests=await Request.find({donorId:req.user._id}).populate('recipientId','name organizationName recipientType city district phone').populate('donationId','title quantity unit status').sort({createdAt:-1});res.json({success:true,data:{requests}});});
export const donationRequests=asyncHandler(async(req,res)=>{if(!mongoose.isValidObjectId(req.params.donationId)) throw new HttpError(400,'Invalid donation ID'); const donation=await Donation.findById(req.params.donationId);if(!donation)throw new HttpError(404,'Donation not found');if(String(donation.donorId)!==String(req.user._id)&&req.user.role!=='ADMIN')throw new HttpError(403,'You cannot view these requests');const requests=await Request.find({donationId:donation._id}).populate('recipientId','name organizationName recipientType city district phone').sort({createdAt:-1});res.json({success:true,data:{requests}});});
export const updateRequestStatus=asyncHandler(async(req,res)=>{const request=await Request.findById(req.params.id).populate('donationId');if(!request)throw new HttpError(404,'Request not found');const {status}=req.body;const isRecipient=String(request.recipientId)===String(req.user._id);const isDonor=String(request.donorId)===String(req.user._id);if(!isRecipient&&!isDonor&&req.user.role!=='ADMIN')throw new HttpError(403,'You cannot change this request');const allowed={PENDING:['ACCEPTED','REJECTED','CANCELLED'],ACCEPTED:['COLLECTED','CANCELLED'],COLLECTED:['COMPLETED'],REJECTED:[],CANCELLED:[],COMPLETED:[]};if(!allowed[request.status]?.includes(status))throw new HttpError(400,`Cannot change request from ${request.status} to ${status}`);if(['ACCEPTED','REJECTED'].includes(status)&&!isDonor&&req.user.role!=='ADMIN')throw new HttpError(403,'Only the donor can accept or reject requests');if(['CANCELLED'].includes(status)&&!isRecipient&&req.user.role!=='ADMIN')throw new HttpError(403,'Only the recipient can cancel a pending request');request.status=status;await request.save();const donation=request.donationId;if(status==='ACCEPTED')donation.status='ACCEPTED';if(status==='COLLECTED')donation.status='COLLECTED';if(status==='COMPLETED')donation.status='COMPLETED';if(status==='REJECTED'){const pending=await Request.countDocuments({donationId:donation._id,status:'PENDING'});donation.status=pending?'REQUESTED':'AVAILABLE';}if(status==='CANCELLED'){const pending=await Request.countDocuments({donationId:donation._id,status:'PENDING'});if(['REQUESTED','AVAILABLE'].includes(donation.status))donation.status=pending?'REQUESTED':'AVAILABLE';}await donation.save();res.json({success:true,message:'Request status updated',data:{request}});});
export const deleteRequest=asyncHandler(async(req,res)=>{const request=await Request.findById(req.params.id);if(!request)throw new HttpError(404,'Request not found');if(String(request.recipientId)!==String(req.user._id))throw new HttpError(403,'You can only cancel your own request');if(request.status!=='PENDING')throw new HttpError(400,'Only pending requests can be cancelled');request.status='CANCELLED';await request.save();const donation=await Donation.findById(request.donationId);if(donation?.status==='REQUESTED'){const pending=await Request.countDocuments({donationId:donation._id,status:'PENDING'});donation.status=pending?'REQUESTED':'AVAILABLE';await donation.save();}res.json({success:true,message:'Request cancelled'});});
